server:
  host: 0.0.0.0
  port: 8081

database:
  dsn: sqlite://./smart_elf.db
  max_idle_conns: 10
  max_open_conns: 100
  debug: true

feishu:
  im_open_api_host: https://open.feishu.cn
  plugin_id: 1
  plugin_secret: 1
  project_api_host: https://project.feishu.cn
  project_web_host: https://project.feishu.cn

logger:
  level: debug
  format: console
